---

- name: Import pre.yml
  ansible.builtin.import_tasks: pre.yml

- name: Import java.yml
  ansible.builtin.import_tasks: java.yml

- name: Import paper.yml
  ansible.builtin.import_tasks: paper.yml
  when: mcs_fork == 'paper'

- name: Import pufferfish.yml
  ansible.builtin.import_tasks: pufferfish.yml
  when: mcs_fork == 'pufferfish'

- name: Import pufferfishplus.yml
  ansible.builtin.import_tasks: pufferfishplus.yml
  when: mcs_fork == 'pufferfishplus'

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml

- name: Import o11y.yml
  ansible.builtin.import_tasks: o11y.yml

- name: Import daily-restart.yml
  ansible.builtin.import_tasks: daily-restart.yml
