---

- name: Import pre.yml
  ansible.builtin.import_tasks: pre.yml

- name: Import java.yml
  ansible.builtin.import_tasks: java.yml

- name: Include fork
  ansible.builtin.import_tasks: forks/{{ mcs_fork }}.yml

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml

- name: Import o11y.yml
  ansible.builtin.import_tasks: o11y.yml

- name: Import daily-restart.yml
  ansible.builtin.import_tasks: daily-restart.yml
