---

- ansible.builtin.import_tasks: pre.yml

- ansible.builtin.import_tasks: java.yml

- ansible.builtin.import_tasks: paper.yml

- ansible.builtin.import_tasks: config.yml

- ansible.builtin.import_tasks: o11y.yml

- ansible.builtin.import_tasks: daily-restart.yml
