---

- name: install prerequisites
  ansible.builtin.apt:
    name:
      - acl
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: create remote_tmp
  ansible.builtin.file:
    name: "{{ ansible_remote_tmp }}"
    state: directory
    mode: '0700'
  become: yes
  become_user: '{{ mcs_user }}'
