---

- name: mcs_reload_systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: mcs_restart
  ansible.builtin.systemd:
    name: mcs
    state: restarted
    enabled: yes
  become: yes
