---

- name: Mcs_reload_systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes

- name: Mcs_restart
  ansible.builtin.systemd:
    name: mcs
    state: restarted
    enabled: '{{ mcs_autostart }}'
  become: yes
